/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTodoForm: typeof import('./src/components/AddTodoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    UiButton: typeof import('./src/components/ui/buttons/UiButton.vue')['default']
    UiButtonBase: typeof import('./src/components/ui/buttons/UiButtonBase.vue')['default']
    UiCheckbox: typeof import('./src/components/ui/inputs/UiCheckbox.vue')['default']
    UiFormControl: typeof import('./src/components/ui/forms/UiFormControl.vue')['default']
    UiFormError: typeof import('./src/components/ui/forms/UiFormError.vue')['default']
    UiFormLabel: typeof import('./src/components/ui/forms/UiFormLabel.vue')['default']
    UiGhostButton: typeof import('./src/components/ui/buttons/UiGhostButton.vue')['default']
    UiIcon: typeof import('./src/components/ui/UiIcon.vue')['default']
    UiIconButton: typeof import('./src/components/ui/buttons/UiIconButton.vue')['default']
    UiLinkButton: typeof import('./src/components/ui/buttons/UiLinkButton.vue')['default']
    UiSwitch: typeof import('./src/components/ui/inputs/UiSwitch.vue')['default']
    UiTextInput: typeof import('./src/components/ui/inputs/UiTextInput.vue')['default']
  }
}
