/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddTodoForm: typeof import('./src/components/AddTodoForm.vue')['default']
    ArkCheckbox: typeof import('@ark-ui/vue')['Checkbox']
    ArkCheckboxControl: typeof import('@ark-ui/vue')['CheckboxControl']
    ArkCheckboxLabel: typeof import('@ark-ui/vue')['CheckboxLabel']
    ArkDialog: typeof import('@ark-ui/vue')['Dialog']
    ArkDialogBackdrop: typeof import('@ark-ui/vue')['DialogBackdrop']
    ArkDialogCloseTrigger: typeof import('@ark-ui/vue')['DialogCloseTrigger']
    ArkDialogContainer: typeof import('@ark-ui/vue')['DialogContainer']
    ArkDialogContent: typeof import('@ark-ui/vue')['DialogContent']
    ArkDialogDescription: typeof import('@ark-ui/vue')['DialogDescription']
    ArkDialogTitle: typeof import('@ark-ui/vue')['DialogTitle']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    EnsureAuthenticated: typeof import('./src/components/convex/EnsureAuthenticated.vue')['default']
    PaginatedQuery: typeof import('./src/components/convex/PaginatedQuery.vue')['default']
    PaginatedQueryInner: typeof import('./src/components/convex/PaginatedQueryInner.vue')['default']
    Query: typeof import('./src/components/convex/Query.vue')['default']
    QueryInner: typeof import('./src/components/convex/QueryInner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceWorkerPrompt: typeof import('./src/components/ServiceWorkerPrompt.vue')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
    TodoListPaginated: typeof import('./src/components/TodoListPaginated.vue')['default']
    UiButton: typeof import('./src/components/ui/buttons/UiButton.vue')['default']
    UiButtonBase: typeof import('./src/components/ui/buttons/UiButtonBase.vue')['default']
    UiCheckbox: typeof import('./src/components/ui/inputs/UiCheckbox.vue')['default']
    UiDrawer: typeof import('./src/components/ui/drawer/UiDrawer.vue')['default']
    UiDrawerContent: typeof import('./src/components/ui/drawer/UiDrawerContent.vue')['default']
    UiDrawerHeader: typeof import('./src/components/ui/drawer/UiDrawerHeader.vue')['default']
    UiFormControl: typeof import('./src/components/ui/forms/UiFormControl.vue')['default']
    UiFormError: typeof import('./src/components/ui/forms/UiFormError.vue')['default']
    UiFormLabel: typeof import('./src/components/ui/forms/UiFormLabel.vue')['default']
    UiGhostButton: typeof import('./src/components/ui/buttons/UiGhostButton.vue')['default']
    UiIcon: typeof import('./src/components/ui/UiIcon.vue')['default']
    UiIconButton: typeof import('./src/components/ui/buttons/UiIconButton.vue')['default']
    UiLinkButton: typeof import('./src/components/ui/buttons/UiLinkButton.vue')['default']
    UiModal: typeof import('./src/components/ui/modal/UiModal.vue')['default']
    UiModalContent: typeof import('./src/components/ui/modal/UiModalContent.vue')['default']
    UiModalHeader: typeof import('./src/components/ui/modal/UiModalHeader.vue')['default']
    UiSimpleDrawer: typeof import('./src/components/ui/drawer/UiSimpleDrawer.vue')['default']
    UiSimpleModal: typeof import('./src/components/ui/modal/UiSimpleModal.vue')['default']
    UiSpinner: typeof import('./src/components/ui/UiSpinner.vue')['default']
    UiSwitch: typeof import('./src/components/ui/inputs/UiSwitch.vue')['default']
    UiTextInput: typeof import('./src/components/ui/inputs/UiTextInput.vue')['default']
    VFocusOn: typeof import('./src/directives/vFocusOn.ts')['default']
  }
}
